import Head from "next/head";

import { useEffect, useState } from "react";
import { getPhotos } from "../api/unsplash";
import useInfiniteScroll from "../hooks/useInfinite";
import styles from "../styles/Index.module.scss";
import Photo from "../components/Photo";
import { ImSpinner9 } from "react-icons/im";
import { Header } from "../components/Header";

export default function Home() {
  const [photos, setPhotos] = useState([]);
  const [page, setPage] = useState(1);

  /* custom hooks  */
  const [isFetching, setIsFetching] = useInfiniteScroll(loadMorePhotos);

  const getInitialPhotos = () => getPhotos().then((data) => setPhotos(data.response.results));

  /* On page load   */
  useEffect(() => getInitialPhotos(), []);

  function loadMorePhotos() {
    getPhotos(page).then((res) => {
      setPhotos([...photos, ...res.response.results]);
      setPage(page + 1);
      setIsFetching(false);
    });
  }

  return (
    <div>
      <Head>
        <title>Photo Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.ico" />
      </Head>

      {isFetching && (
        <div className={styles.loadingSpinner}>
          <ImSpinner9 size={40} />
        </div>
      )}

      <div className={styles.mainContainer}>
        <Header />

        <div className={styles.photosGrid}>
          {photos.map((photo, index) => (
            <Photo photo={photo} key={index}></Photo>
          ))}
        </div>
      </div>
    </div>
  );
}
